/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package net.service.builder.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import net.service.builder.model.StudentEntry;
import net.service.builder.service.StudentEntryLocalService;
import net.service.builder.service.StudentEntryService;
import net.service.builder.service.persistence.StudentEntryPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the student entry local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link net.service.builder.service.impl.StudentEntryLocalServiceImpl}.
 * </p>
 *
 * @author Administrator
 * @see net.service.builder.service.impl.StudentEntryLocalServiceImpl
 * @see net.service.builder.service.StudentEntryLocalServiceUtil
 * @generated
 */
public abstract class StudentEntryLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements StudentEntryLocalService,
		IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link net.service.builder.service.StudentEntryLocalServiceUtil} to access the student entry local service.
	 */

	/**
	 * Adds the student entry to the database. Also notifies the appropriate model listeners.
	 *
	 * @param studentEntry the student entry
	 * @return the student entry that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public StudentEntry addStudentEntry(StudentEntry studentEntry)
		throws SystemException {
		studentEntry.setNew(true);

		return studentEntryPersistence.update(studentEntry, false);
	}

	/**
	 * Creates a new student entry with the primary key. Does not add the student entry to the database.
	 *
	 * @param studentId the primary key for the new student entry
	 * @return the new student entry
	 */
	public StudentEntry createStudentEntry(long studentId) {
		return studentEntryPersistence.create(studentId);
	}

	/**
	 * Deletes the student entry with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param studentId the primary key of the student entry
	 * @return the student entry that was removed
	 * @throws PortalException if a student entry with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public StudentEntry deleteStudentEntry(long studentId)
		throws PortalException, SystemException {
		return studentEntryPersistence.remove(studentId);
	}

	/**
	 * Deletes the student entry from the database. Also notifies the appropriate model listeners.
	 *
	 * @param studentEntry the student entry
	 * @return the student entry that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public StudentEntry deleteStudentEntry(StudentEntry studentEntry)
		throws SystemException {
		return studentEntryPersistence.remove(studentEntry);
	}

	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(StudentEntry.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return studentEntryPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return studentEntryPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return studentEntryPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return studentEntryPersistence.countWithDynamicQuery(dynamicQuery);
	}

	public StudentEntry fetchStudentEntry(long studentId)
		throws SystemException {
		return studentEntryPersistence.fetchByPrimaryKey(studentId);
	}

	/**
	 * Returns the student entry with the primary key.
	 *
	 * @param studentId the primary key of the student entry
	 * @return the student entry
	 * @throws PortalException if a student entry with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public StudentEntry getStudentEntry(long studentId)
		throws PortalException, SystemException {
		return studentEntryPersistence.findByPrimaryKey(studentId);
	}

	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return studentEntryPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the student entries.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of student entries
	 * @param end the upper bound of the range of student entries (not inclusive)
	 * @return the range of student entries
	 * @throws SystemException if a system exception occurred
	 */
	public List<StudentEntry> getStudentEntries(int start, int end)
		throws SystemException {
		return studentEntryPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of student entries.
	 *
	 * @return the number of student entries
	 * @throws SystemException if a system exception occurred
	 */
	public int getStudentEntriesCount() throws SystemException {
		return studentEntryPersistence.countAll();
	}

	/**
	 * Updates the student entry in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param studentEntry the student entry
	 * @return the student entry that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public StudentEntry updateStudentEntry(StudentEntry studentEntry)
		throws SystemException {
		return updateStudentEntry(studentEntry, true);
	}

	/**
	 * Updates the student entry in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param studentEntry the student entry
	 * @param merge whether to merge the student entry with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the student entry that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public StudentEntry updateStudentEntry(StudentEntry studentEntry,
		boolean merge) throws SystemException {
		studentEntry.setNew(false);

		return studentEntryPersistence.update(studentEntry, merge);
	}

	/**
	 * Returns the student entry local service.
	 *
	 * @return the student entry local service
	 */
	public StudentEntryLocalService getStudentEntryLocalService() {
		return studentEntryLocalService;
	}

	/**
	 * Sets the student entry local service.
	 *
	 * @param studentEntryLocalService the student entry local service
	 */
	public void setStudentEntryLocalService(
		StudentEntryLocalService studentEntryLocalService) {
		this.studentEntryLocalService = studentEntryLocalService;
	}

	/**
	 * Returns the student entry remote service.
	 *
	 * @return the student entry remote service
	 */
	public StudentEntryService getStudentEntryService() {
		return studentEntryService;
	}

	/**
	 * Sets the student entry remote service.
	 *
	 * @param studentEntryService the student entry remote service
	 */
	public void setStudentEntryService(StudentEntryService studentEntryService) {
		this.studentEntryService = studentEntryService;
	}

	/**
	 * Returns the student entry persistence.
	 *
	 * @return the student entry persistence
	 */
	public StudentEntryPersistence getStudentEntryPersistence() {
		return studentEntryPersistence;
	}

	/**
	 * Sets the student entry persistence.
	 *
	 * @param studentEntryPersistence the student entry persistence
	 */
	public void setStudentEntryPersistence(
		StudentEntryPersistence studentEntryPersistence) {
		this.studentEntryPersistence = studentEntryPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();

		PersistedModelLocalServiceRegistryUtil.register("net.service.builder.model.StudentEntry",
			studentEntryLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"net.service.builder.model.StudentEntry");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return StudentEntry.class;
	}

	protected String getModelClassName() {
		return StudentEntry.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = studentEntryPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = StudentEntryLocalService.class)
	protected StudentEntryLocalService studentEntryLocalService;
	@BeanReference(type = StudentEntryService.class)
	protected StudentEntryService studentEntryService;
	@BeanReference(type = StudentEntryPersistence.class)
	protected StudentEntryPersistence studentEntryPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private StudentEntryLocalServiceClpInvoker _clpInvoker = new StudentEntryLocalServiceClpInvoker();
}