/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package net.service.builder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the StudentEntry service. Represents a row in the &quot;Student_StudentEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link net.service.builder.model.impl.StudentEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link net.service.builder.model.impl.StudentEntryImpl}.
 * </p>
 *
 * @author Administrator
 * @see StudentEntry
 * @see net.service.builder.model.impl.StudentEntryImpl
 * @see net.service.builder.model.impl.StudentEntryModelImpl
 * @generated
 */
public interface StudentEntryModel extends BaseModel<StudentEntry> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a student entry model instance should use the {@link StudentEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this student entry.
	 *
	 * @return the primary key of this student entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this student entry.
	 *
	 * @param primaryKey the primary key of this student entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the student ID of this student entry.
	 *
	 * @return the student ID of this student entry
	 */
	public long getStudentId();

	/**
	 * Sets the student ID of this student entry.
	 *
	 * @param studentId the student ID of this student entry
	 */
	public void setStudentId(long studentId);

	/**
	 * Returns the name of this student entry.
	 *
	 * @return the name of this student entry
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this student entry.
	 *
	 * @param name the name of this student entry
	 */
	public void setName(String name);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(StudentEntry studentEntry);

	public int hashCode();

	public CacheModel<StudentEntry> toCacheModel();

	public StudentEntry toEscapedModel();

	public StudentEntry toUnescapedModel();

	public String toString();

	public String toXmlString();
}